#!/bin/bash

set -e

if [[ -z "$RACKET_HOME" ]]
then
    echo '$RACKET_HOME is not defined'
    exit 1
fi


cd $(dirname "$0")/..

for script in $(cd rkt && ls *.rkt); do
    echo "Loading $script"
    "$RACKET_HOME"/bin/racket --load "rkt/$script"
done
